# HIT Data science course - exercies 1 + 2

## Setup
Before the course begins, please install **one** of the following environments for writing and running Python code:

### Option 1 – Anaconda
* Anaconda is a platform for working with Python in data science.
* It comes with useful tools like Jupyter Notebook and common data science libraries.
* It helps manage packages and environments for different projects.
#### Please install Anaconda at https://www.anaconda.com/download

### Option 2 – Visual Studio Code
* Visual Studio Code (VS Code) is a code editor developed by Microsoft.
* It helps developers write, organize, run, and debug programs in many programming languages, including Python.
* It also supports extensions that add features such as Jupyter notebooks, Git integration, etc...
#### Please install Visual Studio Code at https://code.visualstudio.com/download?_exp_download=fb315fc982

### Kaggle
* Kaggle is a website where people can learn and practice data science using real datasets. https://www.kaggle.com/
* It has a "Learn" section with lessons and exercises. https://www.kaggle.com/learn
* It has a "Competitions" section where members can participate in data science competitions to practice and improve their skills. https://www.kaggle.com/competitions

#### Please create a Kaggle account, as we will use datasets from Kaggle during the course.
* Downloud "Diamonds.csv" dataset from Kaggle and save it in the "data" folder.

## Getting started- Data science tools and packages

### Pandas
* pandas is a Python library for working with structured data.
* It helps us load, clean, organize, analyze, and save data.
* It is especially useful for data in table format, like Excel files, CSV files, or database tables.
* The main object in pandas is called a DataFrame, which is similar to a table with rows and columns.

In [1]:
import pandas as pd

#### Read Data

* The main object in pandas is called a DataFrame, which is similar to a table with rows and columns.

The following cell of code loads data from a CSV file into a Pandas DataFrame.

note:
* pd.read_csv(...) reads a CSV file using the Pandas library.
* 'data/diamonds.csv' is the location of the file (change it to the location of your CSV file)
* sep=',' tells Pandas that the values in the file are separated by commas.
* index_col=0 tells Pandas to use the first column in the CSV file as the row index instead of treating it as a regular data column.
* diamonds_df = saves the loaded table in a variable called diamonds_df.

After running it, diamonds_df contains the diamonds dataset and can be used for data analysis.

In [2]:
diamonds_df = pd.read_csv('data/diamonds.csv', sep=',' , index_col=0)

* In The following cell, The head() method displays the first rows of a DataFrame.
* Recall that diamonds_df is the DataFrame that contains the diamonds dataset.
* .head(10) tells Pandas to display the first 10 rows of the DataFrame (chane it to display more or fewer rows using a different number).
* This method is commonly used to quickly inspect the data after loading it and verify that it looks correct.

In [3]:
diamonds_df.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

#### OOP

In Object-Oriented Programming (OOP), an attribute is data that belongs to an object, while a method is an action/function that the object can perform.
* An attribute stores information about the object.
* A method is a function inside a class. It usually does something, often using or changing the object’s attributes.
* we access an attribute without parentheses, and a method with parentheses
* in the following 2 cells columns is an attribute (holds the column names of diamonds_df) example and info() is a method example (returns information about the diamonds_df):

In [4]:
diamonds_df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [5]:
diamonds_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

note: float64 and int64 are both numeric data types, but they store different kinds of numbers
* int64 stores whole numbers only - integers.
* float64 stores decimal numbers.
* str (string) is the pandas type for text columns.

### Descriptive statistics

The describe() method generates a statistical summary (Descriptive statistics) of the numeric columns in a DataFrame.

For each numeric column, it displays:

* count – The number of non-missing (NaN) values.
* mean – The average value.
* std – The standard deviation, which measures how spread out the values are.
* min – The smallest value.
* 25% – The first quartile (25% of the values are below this number).
* 50% – The median (the middle value).
* 75% – The third quartile (75% of the values are below this number).
*  max – The largest value.

In [6]:
diamonds_df.describe().round()

         carat    depth    table    price        x        y        z
count  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0
mean       1.0     62.0     57.0   3933.0      6.0      6.0      4.0
std        0.0      1.0      2.0   3989.0      1.0      1.0      1.0
min        0.0     43.0     43.0    326.0      0.0      0.0      0.0
25%        0.0     61.0     56.0    950.0      5.0      5.0      3.0
50%        1.0     62.0     57.0   2401.0      6.0      6.0      4.0
75%        1.0     62.0     59.0   5324.0      7.0      7.0      4.0
max        5.0     79.0     95.0  18823.0     11.0     59.0     32.0

Use include=['str'] to describe string variables instead numeric

In [7]:
diamonds_df.describe(include=['str'])

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

Use unique method to show the unique() possible values in a chosen column, or nunique() to count them

In [8]:
diamonds_df["color"].unique()

<StringArray>
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Length: 7, dtype: str

### choose columns, filter rows & sort values
There are several ways to choose a subset of columns from a DataFrame.
* To show only one chosen column out of diamonds_df use the name of it inside square brackets (or a list of names to show more then one column).

In [9]:
diamonds_df["price"].head()

1    326
2    326
3    327
4    334
5    335
Name: price, dtype: int64

In [10]:
diamonds_df[["color", "price"]].head()

  color  price
1     E    326
2     E    326
3     E    327
4     I    334
5     J    335

* Alternatively, use loc attribute

In [11]:
diamonds_df.loc[:,"price"].head()

1    326
2    326
3    327
4    334
5    335
Name: price, dtype: int64

In [12]:
diamonds_df.loc[:,["color","price"]].head()

  color  price
1     E    326
2     E    326
3     E    327
4     I    334
5     J    335

* You can also choose row with loc attribute, for example chose the 4'th row (note it will be displayed as transpose):

In [13]:
diamonds_df.loc[4]

carat         0.29
cut        Premium
color            I
clarity        VS2
depth         62.4
table         58.0
price          334
x              4.2
y             4.23
z             2.63
Name: 4, dtype: object

* You  can also choose rows 4 - 8

In [14]:
diamonds_df.loc[4:8]

   carat        cut color clarity  depth  table  price     x     y     z
4   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53

* or, choose rows by condition:

In [15]:
diamonds_df.loc[diamonds_df['depth'] < 61]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
10      0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
13      0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
15      0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53931   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53932   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53933   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50

[12360 rows x 10 columns]

In [16]:
diamonds_df['depth'] < 61

1        False
2         True
3         True
4        False
5        False
         ...
53936     True
53937    False
53938    False
53939    False
53940    False
Name: depth, Length: 53940, dtype: bool

* You can sort rows by chosen column using sort values method

In [17]:
diamonds_df.sort_values(by='carat').head()

       carat      cut color clarity  depth  table  price     x     y     z
15       0.2  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
31598    0.2    Ideal     D     VS2   61.5   57.0    367  3.81  3.77  2.33
31597    0.2  Premium     F     VS2   62.6   59.0    367  3.73  3.71  2.33
31596    0.2    Ideal     E     VS2   59.7   55.0    367  3.86  3.84  2.30
31595    0.2  Premium     E     VS2   59.7   62.0    367  3.84  3.80  2.28

In [18]:
diamonds_df.sort_values(by='carat', inplace=True)

### Create new colum in the data frame

In [21]:
diamonds_df["price_per_carat"] = diamonds_df["price"] / diamonds_df["carat"]

diamonds_df["is_expensive"] = diamonds_df["price"] > 10000

In [22]:
import numpy as np
diamonds_df["rate"] = np.where(diamonds_df["price"] > 10000, 'expensive', 'cheap')
diamonds_df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive,rate
15,0.2,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,1725.0,False,cheap
31598,0.2,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,1835.0,False,cheap
31597,0.2,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,1835.0,False,cheap
31596,0.2,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30,1835.0,False,cheap
31595,0.2,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28,1835.0,False,cheap

### Grouping

In [23]:
diamonds_df['price'].mean()

np.float64(3932.799721913237)

In [24]:
diamonds_df.groupby('cut')['price'].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

### Exercises
##### Exercise 1: Basic exploration
1. How many rows and columns are in the dataset?
2. What are the column names?
3. What are the data types of each column?
4. Are there missing values?
5. Show summary statistics for numeric columns.
6. Show summary statistics for categorical columns.

##### Exercise 2: Filtering diamonds

Create filtered DataFrames for the following questions:

1. Diamonds with price greater than 15,000.
2. Diamonds with carat greater than 2.
3. Diamonds with cut == "Ideal" and color == "D".
4. Diamonds with price between 5,000 and 10,000.
5. Diamonds that are either color D or color E.

##### Exercise 3: Sorting and selecting columns

1. Show only the columns: carat, cut, color, clarity, and price.
2. Sort the diamonds by price from highest to lowest.
3. Show the 10 most expensive diamonds.
4. Show the 10 largest diamonds by carat.
5. Find the cheapest diamond with cut == "Ideal".

##### Exercise 4: Grouping and aggregation
calculate:

1. Average price by cut.
2. Average price by color.
3. Average carat by cut.
4. Number of diamonds in each clarity group.
5. Minimum, maximum, and average price by cut.