# Exercise 3

In [1]:
import numpy as np
import pandas as pd
# from prompt_toolkit.layout import dimension

#### Read Data

* The main object in pandas is called a DataFrame, which is similar to a table with rows and columns.

The following cell of code loads data from a CSV file into a Pandas DataFrame.

note:
* pd.read_csv(...) reads a CSV file using the Pandas library.
* 'data/diamonds.csv' is the location of the file (change it to the location of your CSV file)
* sep=',' tells Pandas that the values in the file are separated by commas.
* index_col=0 tells Pandas to use the first column in the CSV file as the row index instead of treating it as a regular data column.
* diamonds_df = saves the loaded table in a variable called diamonds_df.

After running it, diamonds_df contains the diamonds dataset and can be used for data analysis.

In [2]:
diamonds_df = pd.read_csv('data/diamonds.csv', sep=',' , index_col=0)

* In The following cell, The head() method displays the first rows of a DataFrame.
* Recall that diamonds_df is the DataFrame that contains the diamonds dataset.
* .head(10) tells Pandas to display the first 10 rows of the DataFrame (chane it to display more or fewer rows using a different number).
* This method is commonly used to quickly inspect the data after loading it and verify that it looks correct.

In [3]:
diamonds_df.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

### choose columns, filter rows & sort values
There are several ways to choose a subset of columns from a DataFrame.
* To show only one chosen column out of diamonds_df use the name of it inside square brackets (or a list of names to show more than one column).

In [4]:
diamonds_df["cut"]

1            Ideal
2          Premium
3             Good
4          Premium
5             Good
           ...
53936        Ideal
53937         Good
53938    Very Good
53939      Premium
53940        Ideal
Name: cut, Length: 53940, dtype: str

In [5]:
diamonds_df[["color", "price"]]

      color  price
1         E    326
2         E    326
3         E    327
4         I    334
5         J    335
...     ...    ...
53936     D   2757
53937     D   2757
53938     D   2757
53939     H   2757
53940     D   2757

[53940 rows x 2 columns]

* Alternatively, use loc attribute

In [6]:
diamonds_df.loc[:,"cut"]

1            Ideal
2          Premium
3             Good
4          Premium
5             Good
           ...
53936        Ideal
53937         Good
53938    Very Good
53939      Premium
53940        Ideal
Name: cut, Length: 53940, dtype: str

In [7]:
diamonds_df.loc[:,["color","price"]]

      color  price
1         E    326
2         E    326
3         E    327
4         I    334
5         J    335
...     ...    ...
53936     D   2757
53937     D   2757
53938     D   2757
53939     H   2757
53940     D   2757

[53940 rows x 2 columns]

* You can also choose row with loc attribute, for example chose the 4'th row (note it will be displayed as transpose):

In [8]:
diamonds_df.loc[4]

carat         0.29
cut        Premium
color            I
clarity        VS2
depth         62.4
table         58.0
price          334
x              4.2
y             4.23
z             2.63
Name: 4, dtype: object

* You  can also choose rows 4 - 8

In [9]:
diamonds_df.loc[4:8]

   carat        cut color clarity  depth  table  price     x     y     z
4   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53

* or, choose rows by condition:

In [10]:
diamonds_df.loc[diamonds_df['depth'] < 61]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
10      0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
13      0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
15      0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53931   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53932   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53933   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50

[12360 rows x 10 columns]

In [11]:
# note the boolean output inside the []
diamonds_df['depth'] < 61

1        False
2         True
3         True
4        False
5        False
         ...
53936     True
53937    False
53938    False
53939    False
53940    False
Name: depth, Length: 53940, dtype: bool

* You can sort rows by chosen column using sort values method (note the difference between inplace=False/True and .reset_index())

In [12]:
diamonds_df.sort_values(by='carat', ascending=False, inplace=False)

       carat        cut color clarity  depth  table  price      x      y     z
27416   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27631   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27131   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
26000   4.01    Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25999   4.01    Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
31594   0.20    Premium     E     VS2   61.1   59.0    367   3.81   3.78  2.32
31593   0.20    Premium     E     VS2   59.0   60.0    367   3.81   3.78  2.24
31600   0.20      Ideal     E     VS2   62.2   57.0    367   3.76   3.73  2.33
31598   0.20      Ideal     D     VS2   61.5   57.0    367   3.81   3.77  2.33
31599   0.20  Very Good     E     VS2   63.4   59.0    367   3.74   3.71  2.36

[53940 rows x 10 columns]

In [13]:
diamonds_df.sort_values(by='carat', ascending=False, inplace=True)

In [14]:
diamonds_df.reset_index(inplace=True)

### Create new colum in the data frame

In [15]:
diamonds_df["price_per_carat"] = diamonds_df["price"] / diamonds_df["carat"]

diamonds_df["is_expensive"] = diamonds_df["price"] > 10000

diamonds_df

,index,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive
0,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True
1,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True
2,27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True
3,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True
4,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,31594,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,1835.000000,False
53936,31593,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,1835.000000,False
53937,31600,0.20,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33,1835.000000,False
53938,31598,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,1835.000000,False
53939,31599,0.20,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36,1835.000000,False

In [16]:
diamonds_df.shape[0]

53940

In [17]:
diamonds_df.shape[0] - diamonds_df['is_expensive'].sum()

np.int64(48718)

In [18]:
diamonds_df["rate"] = np.where(diamonds_df["price"] > 10000, 'expensive', 'cheap')
diamonds_df.head()

,index,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive,rate
0,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True,expensive
1,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True,expensive
2,27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True,expensive
3,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True,expensive
4,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True,expensive

### Grouping

In [19]:
diamonds_df['price'].mean()

np.float64(3932.799721913237)

In [20]:
diamonds_df['cut'].unique()

<StringArray>
['Fair', 'Premium', 'Very Good', 'Ideal', 'Good']
Length: 5, dtype: str

In [21]:
diamonds_df.groupby('cut')['price'].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [22]:
diamonds_df.groupby('color')['price'].mean()

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

#### Git
* Git tracks changes in a repository (repo) — a project folder.
* Every saved version is called a commit.
* GitHub is a cloud platform to store Git repositories online.
* git push - uploads your local commits to GitHub (the remote repository).
* git pull- downloads new changes from GitHub to your local computer.

### Optional exercises
##### Exercise 1: Basic exploration
1. How many rows and columns are in the dataset?
2. What are the column names?
3. What are the data types of each column?
4. Are there missing values?
5. Show summary statistics for numeric columns.
6. Show summary statistics for categorical columns.

##### Exercise 2: Filtering diamonds

Create filtered DataFrames for the following questions:

1. Diamonds with price greater than 15,000.
2. Diamonds with carat greater than 2.
3. Diamonds with cut == "Ideal" and color == "D".
4. Diamonds with price between 5,000 and 10,000.
5. Diamonds that are either color D or color E.

##### Exercise 3: Sorting and selecting columns

1. Show only the columns: carat, cut, color, clarity, and price.
2. Sort the diamonds by price from highest to lowest.
3. Show the 10 most expensive diamonds.
4. Show the 10 largest diamonds by carat.
5. Find the cheapest diamond with cut == "Ideal".

##### Exercise 4: Grouping and aggregation
calculate:

1. Average price by cut.
2. Average price by color.
3. Average carat by cut.
4. Number of diamonds in each clarity group.
5. Minimum, maximum, and average price by cut.